Repository nanograv/enterprise, pull requests merged in 2023-11, with the labels that each got.

#359 Bugfix for bug #358
  enterprise/signals/gp_signals.py
Labels: bug

#336 add conda stuff to docs
  CONTRIBUTING.rst
  docs/installation.rst
Labels: documentation

#343 Fast Sherman Morrison for Kernel Ecorr
  enterprise/signals/white_signals.py
  requirements_dev.txt
  tests/test_white_signals.py
Labels: enhancement

#356 Allow for index arrays in ShermanMorrison
  enterprise/signals/signal_base.py
  enterprise/signals/utils.py
  enterprise/signals/white_signals.py
  tests/test_utils.py
  tests/test_white_signals.py
Labels: enhancement

#368 Astropy optional
  enterprise/pulsar.py
Labels: bug
